export const Location = [
    {
        parking_lot_name: 'Hùng Vương',
        city: 'TPHCM',
        district: 'Thành phố Thủ Đức',
        ward: 'An Khánh',
        street: 'Tố Hữu',
        lat: 10.783889,
        lng: 106.73472,
    },
    {
        parking_lot_name: 'Hai Bà Trưng',
        city: 'TPHCM',
        district: 'Quận Bình Tân',
        ward: 'An Lạc',
        street: 'Kinh Dương Vương',
        lat: 10.846667,
        lng: 106.77778,
    },
    {
        parking_lot_name: 'Lý Nam Đế',
        city: 'TPHCM',
        district: 'Quận 12',
        ward: 'An Phú Đông',
        street: 'An Phú Đông 3',
        lat: 10.856389,
        lng: 106.7625,
    },
    {
        parking_lot_name: 'Ngô Quyền',
        city: 'TPHCM',
        district: 'Quận 1',
        ward: 'Bến Nghé',
        street: 'Đồng Khởi',
        lat: 10.863889,
        lng: 106.782776,
    },
    {
        parking_lot_name: 'Đinh Bộ Lĩnh',
        city: 'TPHCM',
        district: 'Quận 1',
        ward: 'Bến Thành',
        street: 'Lê Lợi',
        lat: 10.882222,
        lng: 106.76889,
    },
    {
        parking_lot_name: 'Lê Hoàn',
        city: 'TPHCM',
        district: 'Thành phố Thủ Đức',
        ward: 'Bình Chiểu',
        street: 'Ngô Chí Quốc',
        lat: 10.884167,
        lng: 106.73028,
    },
    {
        parking_lot_name: 'Lý Công Uẩn',
        city: 'TPHCM',
        district: 'Quận Bình Tân',
        ward: 'Bình Hưng Hòa',
        street: 'Lê Trọng Tấn',
        lat: 10.843611,
        lng: 106.79139,
    },
    {
        parking_lot_name: 'Lý Thường Kiệt',
        city: 'TPHCM',
        district: 'Quận 1',
        ward: 'Đa Kao',
        street: 'Nguyễn Đình Chiểu',
        lat: 10.81,
        lng: 106.73333,
    },
    {
        parking_lot_name: 'Trần Nhân Tông',
        city: 'TPHCM',
        district: 'Thành phố Thủ Đức',
        ward: 'Hiệp Phú',
        street: 'Man Thiện',
        lat: 10.771944,
        lng: 106.715,
    },
    {
        parking_lot_name: 'Trần Hưng Đạo',
        city: 'TPHCM',
        district: 'Quận Tân Phú',
        ward: 'Hiệp Tân',
        street: 'Hòa Bình',
        lat: 10.833056,
        lng: 106.755,
    },
    {
        parking_lot_name: 'Lê Lợi',
        city: 'TPHCM',
        district: 'Quận 12',
        ward: 'Hiệp Thành',
        street: 'Nguyễn Ánh Thủ',
        lat: 10.782222,
        lng: 106.70278,
    },
    {
        parking_lot_name: 'Nguyễn Trãi',
        city: 'TPHCM',
        district: 'Quận Tân Phú',
        ward: 'Hoà Thạnh',
        street: 'Thoại Ngọc Hầu',
        lat: 10.772521,
        lng: 106.69802,
    },
    {
        parking_lot_name: 'Nguyễn Huệ',
        city: 'TPHCM',
        district: 'Thành phố Thủ Đức',
        ward: 'Linh Chiểu',
        street: 'Tô Vĩnh Diện',
        lat: 10.789167,
        lng: 106.696945,
    },
    {
        parking_lot_name: 'Hồ Chí Minh',
        city: 'TPHCM',
        district: 'Thành phố Thủ Đức',
        ward: 'Linh Trung',
        street: 'Lê Văn Chí',
        lat: 10.783408,
        lng: 106.69077,
    },
    {
        parking_lot_name: 'Võ Nguyên Giáp',
        city: 'TPHCM',
        district: 'Thành phố Thủ Đức',
        ward: 'Linh Xuân',
        street: 'Bà Giang',
        lat: 10.758333,
        lng: 106.735,
    },
    {
        parking_lot_name: 'Nguyễn Chí Thanh',
        city: 'TPHCM',
        district: 'Quận 3',
        ward: 'Phường Võ Thị Sáu',
        street: 'Võ Thị Sáu',
        lat: 10.751667,
        lng: 106.72056,
    },
    {
        parking_lot_name: 'Phạm Xuân Ẩn',
        city: 'TPHCM',
        district: 'Quận 7',
        ward: 'Tân Thuận Đông',
        street: 'Tân Thuận',
        lat: 10.851667,
        lng: 106.69722,
    },
    {
        parking_lot_name: 'Lê Trọng Tấn',
        city: 'TPHCM',
        district: 'Quận 7',
        ward: 'Tân Thuận Tây',
        street: 'Trần Xuân Soạn',
        lat: 10.881111,
        lng: 106.63528,
    },
    {
        parking_lot_name: 'Văn Tiến Dũng',
        city: 'TPHCM',
        district: 'Thành phố Thủ Đức',
        ward: 'Tăng Nhơn Phú A',
        street: 'Lê Văn Việt',
        lat: 10.722222,
        lng: 106.611115,
    },
    {
        parking_lot_name: 'Hoàng Văn Thái',
        city: 'TPHCM',
        district: 'Thành phố Thủ Đức',
        ward: 'Thảo Điền',
        street: 'Quốc Hương',
        lat: 10.8025,
        lng: 106.6,
    },
    {
        parking_lot_name: 'Lê Đức Anh',
        city: 'TPHCM',
        district: 'Thành phố Thủ Đức',
        ward: 'Thủ Thiêm',
        street: 'Mai Chí Thọ',
        lat: 10.768889,
        lng: 106.62666,
    },
    {
        parking_lot_name: 'Chu Huy Mân',
        city: 'TPHCM',
        district: 'Thành phố Thủ Đức',
        ward: 'Trường Thọ',
        street: 'Đặng Văn Bi',
        lat: 10.779167,
        lng: 106.63472,
    },
];

export const District = [
    'Thành phố Thủ Đức',
    'Quận 1',
    'Quận 2',
    'Quận 3',
    'Quận 4',
    'Quận 5',
    'Quận 6',
    'Quận 7',
    'Quận 8',
    'Quận 9',
    'Quận 10',
    'Quận 11',
    'Quận 12',
    'Quận Phú Nhuận',
    'Quận Tân Bình',
    'Quận Tấn Phú',
    'QUận Bình Tân',
    'Huyện Củ Chỉ',
    'Huyện Cần Giờ',
    'Huyện Nhà Bè',
];
